官方标准配置

diff --git a/.github/workflows/openwrt-build.yml b/.github/workflows/openwrt-build.yml
--- a/.github/workflows/openwrt-build.yml
+++ b/.github/workflows/openwrt-build.yml
@@ -69,7 +69,7 @@ jobs:
       - name: Compile Firmware
         run: |
           echo -e "$(nproc) thread compile"
-          make -j$(nproc) V=s || { echo "Compile Firmware Error!"; exit 1; }
+          make -j$(nproc) || { echo "Compile Firmware Error!"; exit 1; }
 
       - name: Upload Firmware Artifact
         uses: actions/upload-artifact@v4
