Update openwrt-build.yml
Signed-off-by: 0230826 <307127899@qq.com>

diff --git a/.github/workflows/openwrt-build.yml b/.github/workflows/openwrt-build.yml
--- a/.github/workflows/openwrt-build.yml
+++ b/.github/workflows/openwrt-build.yml
@@ -20,13 +20,14 @@ jobs:
 
       - name: Install Dependencies
         run: |
-          sudo apt update || { echo "Apt Update Error!"; exit 1; }
-          sudo apt full-upgrade -y || { echo "Apt Upgrade Error!"; exit 1; }
-          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
-              gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
+              sudo apt update || { echo "Apt Update Error!"; exit 1; }
+              sudo apt full-upgrade -y || { echo "Apt Upgrade Error!"; exit 1; }
+              sudo apt install -y python3-apt python3-pip
+              pip3 install setuptools
+              sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
+              gettext git libncurses5-dev libssl-dev rsync unzip zlib1g-dev \
               file wget || { echo "Install Dependencies Error!"; exit 1; }
-          # 清理冗余空间（可选，解决空间不足问题）
-          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
+              sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
 
       - name: Download Source & Feeds (With Retry & Mirror)
         run: |
@@ -78,4 +79,5 @@ jobs:
         with:
           name: OpenWrt_Official_Firmware_${{ github.sha }}
           path: bin/targets/
+
           retention-days: 30
